# OpenKVM Configuration
# See kvm.new.toml for all available options

[websocket]
addr = ":8080"
path = "/websockify"
cors = true
timeout = 30

[vnc]
path = "./noVNC"
username = "openkvm"
password = "CHANGE_ME"

[keyboard]
type = "serialport"
src = "/dev/ttyACM0"
ext = { baud = "921600" }

[video]
type = "shell"
src = [
    "v4l2-ctl",
    "--device=/dev/video0",
    "--stream-mmap",
    "--set-fmt-video=width=1920,height=1080,pixelformat=MJPG",
    "--stream-to=-",
]
width = 1920
height = 1080
frame_rate = 30
quality = 85
slice_count = 4

[mouse]
type = "serialport"
src = "/dev/ttyACM0"
ext = { baud = "921600" }
cursor_x_scale = 17.00
cursor_y_scale = 28.78

[button]
type = "none"

[clipboard]
type = "serialport"
src = "/dev/ttyACM0"
ext = { baud = "921600" }
